site_name: Seqcol Protocol Specification
site_logo: img/seqcol_logo.svg
site_url: http://seqcol.databio.org/
repo_url: http://github.com/ga4gh/seqcol-spec
nav:
  - Getting Started: 
    - Seqcol specification: specification.md
  - Detailed how-to guides:
    - Compute a digest given a SeqCol: digest_from_collection.md
    - Retrieve a SeqCol given a digest: sequences_from_digest.md
    - Compare two sequence collections: compare_collections.md
  - Implementations:
    - Python: implementation_python.md
    - API: implementation_api.md
  - Reference:
    - Decision record: decision_record.md
    - Contributing: contributing.md
theme:
  name: databio
  custom_dir: theme_dir
plugins:
- search
copyright: GA4GH Genomic Knowledge Standards Workstream, Seqcol team
home_link: null
navbar:
  left:
  - text: Specification
    icon: fa-file-alt
    href: specification
  - text: Decision Record
    icon: fa-history
    href: decision_record
  - text: Contributing
    icon: fa-users
    href: contributing
